-- Billy scan proxy. Three small tables, and deliberately nothing about anyone's shopping:
-- trips, receipts and who owes whom stay on the phone.

-- One row per install of the app. The whole point of it existing on a server is that the free
-- trial cannot be reset by clearing site data.
--
-- `used` is a LIFETIME count, not a monthly one. It never resets. A monthly allowance is a
-- recurring bill for every user who never pays; a one-off trial is a single small cost per person.
CREATE TABLE IF NOT EXISTS installs (
  install_id   TEXT PRIMARY KEY,          -- uuid generated by the app on first launch
  month        TEXT NOT NULL,             -- "2026-08", UTC — reporting only; nothing resets on it
  used         INTEGER NOT NULL DEFAULT 0,
  last_scan_at INTEGER,                   -- ms epoch, for the burst check
  created_at   INTEGER NOT NULL
);

-- The brake. One row per UTC day, counting every scan the proxy served to anybody.
--
-- A per-install limit cannot save you from someone who can mint install ids, and nothing stops
-- them until App Attest and Play Integrity exist. This bounds the day's Anthropic bill no matter
-- how the abuse works, which is the only guarantee that actually protects the card behind the key.
CREATE TABLE IF NOT EXISTS daily_spend (
  day        TEXT PRIMARY KEY,            -- "2026-08-14", UTC
  scans      INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL             -- ms epoch
);

-- Written only by verified store receipts and store notifications, never by the app. Empty until
-- in-app purchases ship; the proxy already reads it, so switching subscriptions on is an insert.
--
-- Scan packs will land beside this as a `credits` column or table: the entitlement question the
-- Worker asks is "may this install scan", and a purchased balance is another way to answer yes.
CREATE TABLE IF NOT EXISTS subscriptions (
  install_id              TEXT PRIMARY KEY,
  store                   TEXT NOT NULL,  -- "apple" | "google"
  original_transaction_id TEXT NOT NULL,
  status                  TEXT NOT NULL,  -- "active" | "grace" | "expired" | "refunded"
  current_period_end      INTEGER,        -- ms epoch; null means no known expiry
  updated_at              INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS subscriptions_txn ON subscriptions (original_transaction_id);
