-- Bills scan proxy. Two small tables, and deliberately nothing about anyone's shopping:
-- trips, receipts and who owes whom stay on the phone.

-- One row per install of the app. The whole point of it existing on a server is that the free
-- allowance cannot be reset by clearing site data.
CREATE TABLE IF NOT EXISTS installs (
  install_id   TEXT PRIMARY KEY,          -- uuid generated by the app on first launch
  month        TEXT NOT NULL,             -- "2026-08", UTC
  used         INTEGER NOT NULL DEFAULT 0,
  last_scan_at INTEGER,                   -- ms epoch, for the burst check
  created_at   INTEGER NOT NULL
);

-- Written only by verified store receipts and store notifications, never by the app. Empty until
-- in-app purchases ship; the proxy already reads it, so switching subscriptions on is an insert.
CREATE TABLE IF NOT EXISTS subscriptions (
  install_id              TEXT PRIMARY KEY,
  store                   TEXT NOT NULL,  -- "apple" | "google"
  original_transaction_id TEXT NOT NULL,
  status                  TEXT NOT NULL,  -- "active" | "grace" | "expired" | "refunded"
  current_period_end      INTEGER,        -- ms epoch; null means no known expiry
  updated_at              INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS subscriptions_txn ON subscriptions (original_transaction_id);
