-- Billy scan proxy. Three small tables, and deliberately nothing about anyone's shopping:
-- trips, receipts and who owes whom stay on the phone.

-- One row per install of the app. The whole point of it existing on a server is that the free
-- trial cannot be reset by clearing site data.
--
-- `used` is a LIFETIME count, not a monthly one. It never resets. A monthly allowance is a
-- recurring bill for every user who never pays; a one-off trial is a single small cost per person.
CREATE TABLE IF NOT EXISTS installs (
  install_id   TEXT PRIMARY KEY,          -- uuid generated by the app on first launch
  month        TEXT NOT NULL,             -- "2026-08", UTC — reporting only; nothing resets on it
  used         INTEGER NOT NULL DEFAULT 0,
  -- Scans bought in a pack. Written ONLY after a store receipt has been verified server-side;
  -- there is deliberately no endpoint a client can call to give itself credits.
  credits      INTEGER NOT NULL DEFAULT 0,
  last_scan_at INTEGER,                   -- ms epoch, for the burst check
  -- Whether this install has ever completed a purchase. Drives the first-pack bonus, and is the
  -- reason the bonus cannot be farmed: the client never writes this, and the same UPDATE that
  -- grants the bonus sets it, so the two can never disagree. Refunds deliberately leave it at 1 —
  -- somebody who bought and refunded has bought before.
  has_purchased INTEGER NOT NULL DEFAULT 0,
  created_at   INTEGER NOT NULL
);

-- For a database created before credits existed, run this once (SQLite has no
-- ADD COLUMN IF NOT EXISTS, so it errors harmlessly on a table that already has it):
-- ALTER TABLE installs ADD COLUMN credits INTEGER NOT NULL DEFAULT 0;
-- ALTER TABLE installs ADD COLUMN has_purchased INTEGER NOT NULL DEFAULT 0;

-- The brake. One row per UTC day, counting every scan the proxy served to anybody.
--
-- A per-install limit cannot save you from someone who can mint install ids, and nothing stops
-- them until App Attest and Play Integrity exist. This bounds the day's Anthropic bill no matter
-- how the abuse works, which is the only guarantee that actually protects the card behind the key.
CREATE TABLE IF NOT EXISTS daily_spend (
  day        TEXT PRIMARY KEY,            -- "2026-08-14", UTC
  scans      INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL             -- ms epoch
);

-- What scanning actually costs, per day and per model. No install id, and no timestamp finer than
-- the day: this answers "what does a scan cost" and cannot answer "when does this person shop".
-- One row per day per model, so it stays small enough to read at a glance.
CREATE TABLE IF NOT EXISTS scan_stats (
  day           TEXT NOT NULL,            -- "2026-08-14", UTC
  model         TEXT NOT NULL,
  scans         INTEGER NOT NULL DEFAULT 0,   -- completed successfully
  failures      INTEGER NOT NULL DEFAULT 0,   -- refused, unparseable, or an API error
  input_tokens  INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  cost_micros   INTEGER NOT NULL DEFAULT 0,   -- millionths of a dollar; integers, so sums do not drift
  total_ms      INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, model)
);

-- Every purchase notification that has already been acted on.
--
-- Webhooks are delivered at least once, not exactly once: RevenueCat retries anything it is not
-- sure arrived, and a retry that grants a second pack is free scans for whoever notices. The event
-- id is the store's own, so a replay of a message from an hour ago is recognised as one.
CREATE TABLE IF NOT EXISTS processed_events (
  event_id     TEXT PRIMARY KEY,
  install_id   TEXT NOT NULL,
  product_id   TEXT NOT NULL,
  scans        INTEGER NOT NULL,       -- negative for a refund
  processed_at INTEGER NOT NULL        -- ms epoch
);

-- Written only by verified store receipts and store notifications, never by the app. Empty until
-- in-app purchases ship; the proxy already reads it, so switching subscriptions on is an insert.
CREATE TABLE IF NOT EXISTS subscriptions (
  install_id              TEXT PRIMARY KEY,
  store                   TEXT NOT NULL,  -- "apple" | "google"
  original_transaction_id TEXT NOT NULL,
  status                  TEXT NOT NULL,  -- "active" | "grace" | "expired" | "refunded"
  current_period_end      INTEGER,        -- ms epoch; null means no known expiry
  updated_at              INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS subscriptions_txn ON subscriptions (original_transaction_id);

-- A split published for other phones to read, and the answers they write back.
--
-- The server is a POSTBOX, NOT A RECORD. The host's phone remains the source of truth; this is a
-- copy that exists so four people can look at the same list of items. It is deleted after seven
-- days, and that expiry is what the privacy policy rests on — so nothing here may outlive it.
CREATE TABLE IF NOT EXISTS shared_splits (
  code       TEXT PRIMARY KEY,        -- the code from the invite link
  host_token TEXT NOT NULL,           -- only this may update or revoke; guests never see it
  payload    TEXT NOT NULL,           -- the split as JSON
  created_at INTEGER NOT NULL,        -- ms epoch
  expires_at INTEGER NOT NULL         -- created_at + 7 days
);

CREATE INDEX IF NOT EXISTS shared_splits_expiry ON shared_splits (expires_at);

-- One row per phone that joined a split, holding that phone's own answer.
--
-- Each phone owns exactly its own row, which is why no two writers ever contend: there is nothing
-- shared to contend over. Merging happens on the host's phone, from the union of these rows.
CREATE TABLE IF NOT EXISTS split_participants (
  code       TEXT NOT NULL,
  install_id TEXT NOT NULL,
  person_id  TEXT NOT NULL,              -- which person on the split this phone claims to be
  claims     TEXT NOT NULL DEFAULT '[]', -- JSON array of item ids
  joined_at  INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (code, install_id)
);

-- "A name can only be taken once", enforced where it cannot be raced. Checking in application code
-- first would let two phones both read "Ana is free" and both take her.
CREATE UNIQUE INDEX IF NOT EXISTS split_person_once ON split_participants (code, person_id);
