/**
 * How many scans an install has left this month.
 *
 * Pure on purpose: this is the rule that decides whether someone is asked to pay, so it is
 * worth being able to test every edge of it without a database or a network. The Worker reads
 * a row, calls `decideQuota`, and writes the result back.
 *
 * It lives on the server because it has to. `localStorage.clear()` is an infinite supply of
 * free scans, and clearing site data is a normal thing for a person to do.
 */

export const FREE_SCANS_PER_MONTH = 5;

/** UTC, so the allowance does not reset twice for someone who flies across a timezone. */
export function monthKey(now: Date): string {
  return `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}`;
}

export type QuotaRow = { month: string; used: number };

export type QuotaDecision = {
  allowed: boolean;
  /** Scans used this month after this decision is applied. */
  used: number;
  /** Scans remaining, or null when the install is subscribed and has no cap. */
  left: number | null;
  month: string;
  /** True when the stored row is for an older month and the caller should reset it. */
  rolledOver: boolean;
};

/**
 * Whether this install may scan right now, and what its counters become.
 *
 * `subscribed` short-circuits the cap but still counts, so there is a usage figure to look at
 * when deciding whether five is the right number — and so a subscription that lapses does not
 * suddenly reveal a hidden pile of used scans.
 */
export function decideQuota(
  row: QuotaRow | null,
  now: Date,
  subscribed: boolean,
  limit: number = FREE_SCANS_PER_MONTH
): QuotaDecision {
  const month = monthKey(now);
  const rolledOver = row !== null && row.month !== month;
  // A negative or fractional stored count means the row was tampered with or written by an
  // older version: treat it as unusable rather than as free scans.
  const stored = row === null || rolledOver || !Number.isInteger(row.used) || row.used < 0 ? 0 : row.used;

  const allowed = subscribed || stored < limit;
  const used = allowed ? stored + 1 : stored;
  return {
    allowed,
    used,
    left: subscribed ? null : Math.max(0, limit - used),
    month,
    rolledOver,
  };
}

/** The same question without spending a scan, for the counter the app shows. */
export function peekQuota(
  row: QuotaRow | null,
  now: Date,
  subscribed: boolean,
  limit: number = FREE_SCANS_PER_MONTH
): { used: number; left: number | null; month: string } {
  const month = monthKey(now);
  const stored =
    row === null || row.month !== month || !Number.isInteger(row.used) || row.used < 0 ? 0 : row.used;
  return { used: stored, left: subscribed ? null : Math.max(0, limit - stored), month };
}

/**
 * An install id is only ever generated by the app, so anything that is not the shape we issue
 * is either a mistake or someone poking at the endpoint. Rejecting it keeps the table from
 * filling with junk keys that each carry their own free allowance.
 */
export function isValidInstallId(id: string | null | undefined): boolean {
  return typeof id === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
}
